MODEL:
  NAME: 'resnet50' 
  PRETRAIN_PATH: 'RESNET_PATH'
  #ResNet50 Pretrained Model Path, eg "/home/gutianpei/.cache/torch/hub/checkpoints/resnet50-19c8e357.pth"

APNET:
  LEVEL: 2

INPUT:
  SIZE_TRAIN: [384, 192]
  SIZE_TEST: [384, 192]
  PROB: 0.5 # random horizontal flip
  PADDING: 10

DATASETS:
  NAMES: ('market1501') #select from "dukemtmc", "market1501" and "msmt17"

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'Adam'
  MAX_EPOCHS: 160
  BASE_LR: 0.0004
  BIAS_LR_FACTOR: 1
  WEIGHT_DECAY: 0.001
  WEIGHT_DECAY_BIAS: 0.001
  SMOOTH: 0.1
  IMS_PER_BATCH: 80

  STEPS: [40, 80, 120, 160]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 10
  WARMUP_METHOD: 'linear'
#   CLASSNUM: 1019

  CHECKPOINT_PERIOD: 10
  LOG_PERIOD: 100
  EVAL_PERIOD: 40


TEST:
  IMS_PER_BATCH: 512
  RE_RANK: False
  WEIGHT: "path"

OUTPUT_DIR: "/home/gutianpei/ivg/github_temp/att/Market/"
# /home/gtp_cgy/ivg/dataset/Occluded-DukeMTMC-Dataset/Occluded_Duke
